"""Initial migration

Revision ID: 8b745987107c
Revises: 
Create Date: 2026-01-08 16:37:20.471056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8b745987107c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create ENUM types idempotently (checkfirst=True prevents duplicate errors)
    vendor_enum = postgresql.ENUM('CISCO_ASA', 'CISCO_IOS', 'FORTINET', 'PALO_ALTO', name='vendortype')
    vendor_enum.create(op.get_bind(), checkfirst=True)
    
    environment_enum = postgresql.ENUM('PROD', 'DEV', 'TEST', 'STAGING', 'LAB', 'CLOUD', 'DMZ', name='environmenttype')
    environment_enum.create(op.get_bind(), checkfirst=True)
    
    rulecategory_enum = postgresql.ENUM('ACL', 'NAT', 'VPN', 'ROUTING', 'INTERFACE', 'CRYPTO', 'AUTHENTICATION', 'GENERAL', name='rulecategory')
    rulecategory_enum.create(op.get_bind(), checkfirst=True)
    
    ruleseverity_enum = postgresql.ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='ruleseverity')
    ruleseverity_enum.create(op.get_bind(), checkfirst=True)
    
    # Create ENUM types without create_type for use in table definitions
    vendor_enum_nocreate = postgresql.ENUM('CISCO_ASA', 'CISCO_IOS', 'FORTINET', 'PALO_ALTO', name='vendortype', create_type=False)
    environment_enum_nocreate = postgresql.ENUM('PROD', 'DEV', 'TEST', 'STAGING', 'LAB', 'CLOUD', 'DMZ', name='environmenttype', create_type=False)
    rulecategory_enum_nocreate = postgresql.ENUM('ACL', 'NAT', 'VPN', 'ROUTING', 'INTERFACE', 'CRYPTO', 'AUTHENTICATION', 'GENERAL', name='rulecategory', create_type=False)
    ruleseverity_enum_nocreate = postgresql.ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='ruleseverity', create_type=False)
    
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('mgmt_ip', sa.String(length=45), nullable=True),
    sa.Column('vendor', vendor_enum_nocreate, nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('environment', environment_enum_nocreate, nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('last_audit_id', sa.Integer(), nullable=True),
    sa.Column('last_risk_score', sa.Float(), nullable=True),
    sa.Column('last_policy_hygiene_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['last_audit_id'], ['audit_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_environment'), 'devices', ['environment'], unique=False)
    op.create_index(op.f('ix_devices_hostname'), 'devices', ['hostname'], unique=False)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_mgmt_ip'), 'devices', ['mgmt_ip'], unique=False)
    op.create_index(op.f('ix_devices_site'), 'devices', ['site'], unique=False)
    op.create_index(op.f('ix_devices_vendor'), 'devices', ['vendor'], unique=False)
    op.create_table('rule_packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_packs_category'), 'rule_packs', ['category'], unique=False)
    op.create_index(op.f('ix_rule_packs_enabled'), 'rule_packs', ['enabled'], unique=False)
    op.create_index(op.f('ix_rule_packs_id'), 'rule_packs', ['id'], unique=False)
    op.create_index(op.f('ix_rule_packs_is_builtin'), 'rule_packs', ['is_builtin'], unique=False)
    op.create_index(op.f('ix_rule_packs_name'), 'rule_packs', ['name'], unique=True)
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vendor', sa.String(length=50), nullable=True),
    sa.Column('category', rulecategory_enum_nocreate, nullable=False),
    sa.Column('match_criteria', sa.JSON(), nullable=False),
    sa.Column('severity', ruleseverity_enum_nocreate, nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('previous_rule_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_category'), 'rules', ['category'], unique=False)
    op.create_index(op.f('ix_rules_enabled'), 'rules', ['enabled'], unique=False)
    op.create_index(op.f('ix_rules_id'), 'rules', ['id'], unique=False)
    op.create_index(op.f('ix_rules_name'), 'rules', ['name'], unique=False)
    op.create_index(op.f('ix_rules_severity'), 'rules', ['severity'], unique=False)
    op.create_index(op.f('ix_rules_vendor'), 'rules', ['vendor'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_source', sa.String(length=50), nullable=False),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_actor_id'), 'activity_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_activity_logs_resource_id'), 'activity_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_resource_type'), 'activity_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_timestamp'), 'activity_logs', ['timestamp'], unique=False)
    op.create_table('device_rule_packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('rule_pack_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['rule_pack_id'], ['rule_packs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_rule_packs_device_id'), 'device_rule_packs', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_rule_packs_id'), 'device_rule_packs', ['id'], unique=False)
    op.create_index(op.f('ix_device_rule_packs_rule_pack_id'), 'device_rule_packs', ['rule_pack_id'], unique=False)
    op.create_table('rule_pack_rules',
    sa.Column('rule_pack_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.ForeignKeyConstraint(['rule_pack_id'], ['rule_packs.id'], ),
    sa.PrimaryKeyConstraint('rule_pack_id', 'rule_id')
    )
    op.add_column('api_keys', sa.Column('key_hash', sa.String(length=255), nullable=False))
    op.add_column('api_keys', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_api_keys_key', table_name='api_keys')
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.drop_column('api_keys', 'key')
    op.add_column('config_files', sa.Column('device_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_config_files_device_id'), 'config_files', ['device_id'], unique=False)
    op.create_foreign_key(None, 'config_files', 'devices', ['device_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'config_files', type_='foreignkey')
    op.drop_index(op.f('ix_config_files_device_id'), table_name='config_files')
    op.drop_column('config_files', 'device_id')
    op.add_column('api_keys', sa.Column('key', sa.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.create_index('ix_api_keys_key', 'api_keys', ['key'], unique=1)
    op.drop_column('api_keys', 'last_used_at')
    op.drop_column('api_keys', 'key_hash')
    op.drop_table('rule_pack_rules')
    op.drop_index(op.f('ix_device_rule_packs_rule_pack_id'), table_name='device_rule_packs')
    op.drop_index(op.f('ix_device_rule_packs_id'), table_name='device_rule_packs')
    op.drop_index(op.f('ix_device_rule_packs_device_id'), table_name='device_rule_packs')
    op.drop_table('device_rule_packs')
    op.drop_index(op.f('ix_activity_logs_timestamp'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_resource_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_resource_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_actor_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_rules_vendor'), table_name='rules')
    op.drop_index(op.f('ix_rules_severity'), table_name='rules')
    op.drop_index(op.f('ix_rules_name'), table_name='rules')
    op.drop_index(op.f('ix_rules_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_enabled'), table_name='rules')
    op.drop_index(op.f('ix_rules_category'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_rule_packs_name'), table_name='rule_packs')
    op.drop_index(op.f('ix_rule_packs_is_builtin'), table_name='rule_packs')
    op.drop_index(op.f('ix_rule_packs_id'), table_name='rule_packs')
    op.drop_index(op.f('ix_rule_packs_enabled'), table_name='rule_packs')
    op.drop_index(op.f('ix_rule_packs_category'), table_name='rule_packs')
    op.drop_table('rule_packs')
    op.drop_index(op.f('ix_devices_vendor'), table_name='devices')
    op.drop_index(op.f('ix_devices_site'), table_name='devices')
    op.drop_index(op.f('ix_devices_mgmt_ip'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_hostname'), table_name='devices')
    op.drop_index(op.f('ix_devices_environment'), table_name='devices')
    op.drop_table('devices')
    
    # Drop ENUM types idempotently (checkfirst=True prevents errors if already dropped)
    vendor_enum = postgresql.ENUM('CISCO_ASA', 'CISCO_IOS', 'FORTINET', 'PALO_ALTO', name='vendortype')
    vendor_enum.drop(op.get_bind(), checkfirst=True)
    
    environment_enum = postgresql.ENUM('PROD', 'DEV', 'TEST', 'STAGING', 'LAB', 'CLOUD', 'DMZ', name='environmenttype')
    environment_enum.drop(op.get_bind(), checkfirst=True)
    
    rulecategory_enum = postgresql.ENUM('ACL', 'NAT', 'VPN', 'ROUTING', 'INTERFACE', 'CRYPTO', 'AUTHENTICATION', 'GENERAL', name='rulecategory')
    rulecategory_enum.drop(op.get_bind(), checkfirst=True)
    
    ruleseverity_enum = postgresql.ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='ruleseverity')
    ruleseverity_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
